---
title: "Proposal of P8105 Final Project"
date: "2023-11-07"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Participants
* Lu Qiu (lq2234)
* Zhiyi Zhu (zz3167)
* Chen Liang (cl4469)
* Ziqiu Liu (zl3386)
* Ruoxi Li (rl3401)

### Tentative Project title

Global Volcanic Eruption

### Motivation 

Recently, a striking news about the volcano eruption in Iceland caught our attention. Motivated by the need to better understand and analyze the impact of such natural phenomena, we aim to delve into the patterns, trends, and factors surrounding volcanic eruptions, utilizing data science techniques to extract meaningful insights. 


### Intended final products

* A website with homepage for overview of our project, a page for exploratory analyses, a page for statistical analyses, and a page for project report.
* A detailed project report.
* A two-minute narrated screencast illustrating our project.

### Data sources

* We plan to use the open data set [Significant Volcanic Eruption Database](https://public.opendatasoft.com/explore/dataset/significant-volcanic-eruption-database/table). The Significant Volcanic Eruption Database is a global listing of over 500 significant eruptions which includes information on the latitude, longitude, elevation, type of volcano, and last known eruption. A significant eruption is classified as one that meets at least one of the following criteria: caused fatalities, caused moderate damage (approximately $1 million or more), with a Volcanic Explosivity Index (VEI) of 6 or larger, caused a tsunami, or was associated with a major earthquake.


### Planned Analyses / visualizations / coding challenges


**Visualizations:**

* EDA Plots: Create plots, including at least three distinct plot types (e.g. scatterplots, line plots, bar plots, box plots, etc.).
  
**Analyses:**

* Hypothesis Test: 
* Linear Regression: Fit a linear model

**Challenges:**

* Addressing Missing Data:
Within our extensive dataset, a substantial number of variables exhibit missing values.
* Enhancing Variable Selection:
As we strive to comprehensively examine aspects of stress level, depression score, anxiety score, and beyond, it is essential to broaden the spectrum of variables in our dataset.
* Data Quality Issues:
We need to ensure the quality of the data is crucial. Data may contain errors, outliers, or inconsistencies that can lead to biased or inaccurate results. 
* Website Design:
We plan to create a state-of-the-art website with advanced features and a visually appealing design.

### Planned timeline

* 11.11 Proposal
* 11.13~11.17 Project review meeting
* 11.18~11.21 Finish exploratory analyses
* 11.22~11.25 Finish statistical analyses
* 11.26~11.30 Begin to write the report
* 12.1~12.9 Finish the report and screencast



