---
title: "Statistical Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(MASS)
library(tidyverse)

```
## Data Cleaning and Processing

(Describe the steps in data cleaning)

```{r}
tidy_df = 
  read.csv(
    "data/significant-volcanic-eruption-database.csv", 
    sep = ";", na.strings=c("", NA)) |>
  janitor::clean_names() |>
  select(
    -c(month, day, location, status, volcano_missing, volcano_missing_description, earthquakes_houses_damaged_description),
    -starts_with("total")
    ) |>
  mutate( # change flags to boolean
    flag_tsunami = case_match(flag_tsunami, "Tsunami"~ TRUE, NA ~ FALSE),
    flag_earthquake = case_match(flag_earthquake, "Earthquake"~ TRUE, NA ~ FALSE)
  ) |>
  separate(coordinates, into = c("lat", "long"), sep = ",") |>
  mutate(
    lat = as.numeric(lat), long = as.numeric(long)
  ) |>
  mutate_at(vars(ends_with('description')), ~ifelse(is.na(.), "None/No Record", .)) |>
  mutate( # correct injuries description
    volcano_injuries_description = case_match(
      volcano_injuries_description,
      "Very Many (~1001 or more deaths)" ~ "Very Many (~1001 or more injuries)", 
      "Many (~101 to 1000 deaths)" ~ "Many (~101 to 1000 injuries)", 
      "Some (~51 to 100 deaths)" ~ "Some (~51 to 100 injuries)", 
      "Few (~1 to 50 deaths)" ~ "Few (~1 to 50 injuries)",
      "None/No Record" ~ "None/No Record"
    )
  ) |>
  mutate( # change descriptions to factors w/ levels
    volcano_deaths_description = factor(volcano_deaths_description, levels = c("Very Many (~1001 or more deaths)", "Many (~101 to 1000 deaths)", "Some (~51 to 100 deaths)", "Few (~1 to 50 deaths)", "None/No Record")),
    volcano_injuries_description = factor(volcano_injuries_description, levels = c("Very Many (~1001 or more injuries)", "Many (~101 to 1000 injuries)", "Some (~51 to 100 injuries)", "Few (~1 to 50 injuries)", "None/No Record")),
    volcano_damage_description = factor(volcano_damage_description, levels = c("EXTREME (~$25 million or more)", "SEVERE (~>$5 to $24 million)", "MODERATE (~$1 to $5 million)", "LIMITED (roughly corresponding to less than $1 million)", "None/No Record")),
    volcano_houses_destroyed_description = factor(volcano_houses_destroyed_description, levels = c("Very Many (~1001 or more houses)", "Many (~101 to 1000 houses)", "Some (~51 to 100 houses)", "Few (~1 to 50 houses)", "None/No Record"))
  )

```


## Fit Model(Draft)

```{r}

#相关性分析


#交互项

model1 <- polr(volcano_deaths_description~flag_earthquake*flag_tsunami,data = tidy_df)
summary(model1)

ctable123 <- coef(summary(model1))

p <- pnorm(abs(ctable123[, "t value"]), lower.tail = FALSE) * 2

(ctable <- cbind(ctable123, "p value" = p))

# not reject H0, keep flag_earthquake, flag_tsunami

#看significance要不要
  
## fit ordered logit model and store results 'm'
m <- polr(volcano_deaths_description ~ flag_earthquake + flag_tsunami + volcanic_explosivity_index+elevation, data = tidy_df, Hess=TRUE)

## view a summary of the model
summary(m)

ctable <- coef(summary(m))

p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

(ctable <- cbind(ctable, "p value" = p))

# default method gives profiled CIs
(ci <- confint(m)) 

# CIs assuming normality
confint.default(m) 

## odds ratios
exp(coef(m))

## OR and CI
exp(cbind(OR = coef(m), ci))

```